name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout specific repo
        uses: actions/checkout@v2
        with:
          repository: Birbalsarva/node-todo-cicd  # No need for path if files are in root

      - name: Build Docker image
        run: |
          docker build -t my-app .

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 my-app 
